# Generated by Django 3.0.6 on 2020-07-01 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_blog_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='ctatagory',
            field=models.CharField(default='Fashion', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 18, 58, 35, 317673)),
        ),
    ]
