# Generated by Django 3.0.6 on 2020-07-01 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20200701_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='ctatagory',
            new_name='catagory',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 19, 0, 59, 200572)),
        ),
    ]
