# Generated by Django 3.0.6 on 2020-07-07 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_auto_20200707_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 15, 52, 33, 246240)),
        ),
    ]
