# Generated by Django 3.0.6 on 2020-07-09 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_auto_20200708_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 23, 51, 26, 215893)),
        ),
    ]
