# Generated by Django 3.0.6 on 2020-07-09 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_auto_20200709_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 0, 3, 17, 845476)),
        ),
    ]
