# Generated by Django 3.0.6 on 2020-07-13 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_auto_20200710_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 52, 25, 899815)),
        ),
    ]
