# Generated by Django 3.0.6 on 2020-07-13 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_auto_20200714_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ta',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 52, 50, 420690)),
        ),
    ]
