# Generated by Django 3.0.6 on 2020-07-13 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_auto_20200714_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='tags',
            field=models.ManyToManyField(to='Blog.Tag'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 53, 45, 588934)),
        ),
    ]
