# Generated by Django 3.0.6 on 2020-07-13 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_auto_20200714_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 1, 49, 34, 967052)),
        ),
    ]
