# Generated by Django 3.0.6 on 2020-07-13 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0027_auto_20200714_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 2, 1, 42, 724571)),
        ),
    ]
