# Generated by Django 3.0.6 on 2020-07-16 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0036_auto_20200716_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 11, 55, 212762)),
        ),
    ]
