# Generated by Django 3.0.6 on 2020-07-16 13:33

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0040_auto_20200716_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='thumbnaiil_img',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, keep_meta=True, quality=100, size=[410, 280], upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='cover_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[1030, 550], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='img_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[330, 250], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='img_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[330, 250], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='img_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[330, 250], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='img_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[330, 250], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='img_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[330, 250], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='img_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[330, 250], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 33, 49, 228053)),
        ),
    ]
