# Generated by Django 3.0.6 on 2020-07-16 13:50

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0041_auto_20200716_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='auther_thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[91, 89], upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 50, 51, 37923)),
        ),
    ]
