# Generated by Django 3.0.6 on 2020-07-19 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0042_auto_20200716_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 23, 21, 41, 205713)),
        ),
    ]
