# Generated by Django 3.0.6 on 2020-07-19 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0043_auto_20200719_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 23, 22, 9, 238235)),
        ),
    ]
