# Generated by Django 3.0.6 on 2020-07-07 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_itemcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('issue_date', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_date', models.DurationField()),
                ('discount', models.FloatField(help_text='In Percsent')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_coupen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Coupen'),
        ),
    ]
