# Generated by Django 3.0.6 on 2020-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_auto_20200707_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_coupen',
        ),
        migrations.AddField(
            model_name='item',
            name='item_coupen',
            field=models.ManyToManyField(to='Home.Coupen'),
        ),
    ]
