# Generated by Django 3.0.6 on 2020-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_auto_20200707_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='discount',
            field=models.IntegerField(help_text='In Percsent'),
        ),
    ]
