# Generated by Django 3.0.6 on 2020-07-16 12:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_auto_20200716_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[270, 330], upload_to=''),
        ),
    ]
