# Generated by Django 3.0.6 on 2020-07-16 13:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_auto_20200716_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_zoom_pic1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[130, 87], upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_zoom_pic2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[130, 87], upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_zoom_pic3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[130, 87], upload_to=''),
        ),
    ]
