# Generated by Django 3.0.6 on 2020-07-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20200710_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
