# Generated by Django 3.0.6 on 2020-07-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0003_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('Full_Name', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=30)),
                ('Street_Adress', models.CharField(max_length=2000)),
                ('Post_Code', models.IntegerField()),
                ('City_or_Town', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Phone', models.IntegerField(verbose_name='Contact Number')),
                ('ordering_date', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.TextField(max_length=50000)),
                ('ordering_date', models.DateTimeField(blank=True, default='', null=True)),
                ('Billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Order_Detail')),
            ],
        ),
    ]
