# Generated by Django 3.0.6 on 2020-07-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_order_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordering_date',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='ordering_date',
        ),
    ]
